### PR TITLE
Please review my changes and merge

### PR DESCRIPTION
**Pull request by ghost**
Summary of changes
- Exposing the ability to query by primary key + index and range to CassandraTemplate so it could be used by Spring apps

### CODE REVIEW

**Comment by otaviojava** [comment]
Done.

**Comment by otaviojava** [comment]
On weekend I will generate the new version.

**Comment by ghost** [comment]
Perfect. Thank you so much!

**Comment by ghost** [comment]
Hi @otaviojava, 

Any chance that the latest jar is now available in the repository? Thanks

**Comment by otaviojava** [comment]
Done and updated the version.

**Comment by ghost** [comment]
Great! Thank you so much

**Pull request merged**
