### PR TITLE
enable for multipal index column

### PR DESCRIPTION
**Pull request by dinushadev**
Hi,
I enable Easy-Cassandra ORM mapping for multiparty indexes. If you thing this is useful add it. Contact me if you wont.  

email dnsw83@gmail.com

Best Regards , 
Dinusha Nandika

### CODE REVIEW

**Comment by otaviojava** [comment]
It's great!!
Congratulations and well done.
But in ColumnUtil.java on method public Field getFieldByColumnName(String columnName,Class<?> class1) use exception printstraketrace is not a good practice.
What do you think create an exception and use it in this point ? Also add it in the log.

**Comment by otaviojava** [comment]
that is cool

**Comment by otaviojava** [comment]
thank you and I hope see you again.

**Comment by dinushadev** [comment]
Yes. thank you for contributing me. see you too.

**Pull request merged**
