### PR TITLE
Please review my changes and merge

### PR DESCRIPTION
**Pull request by ghost**
Summary of changes:
- Allow embedded id from the mapped superclass to be used during insertion and query [Fix bug wherein during insertion, an embedded id from a mapped superclass is not honored
  in the subclass]
- Added ability to query by primary key + index
- Added ability to query by primary key + index range
- Sorry about the white space changes. It seems like my Intellij has different tabbing and line separator and I must have accidentally formatted some of the classes while adding my changes. 

NOTE: To run my additional tests properly, please execute in your local Cassandra the following first:
CREATE TABLE lifestyle (personid bigint, companyid int, type int, date timestamp, value double,
primary key ((personid, companyid, type),date));

### CODE REVIEW

**Comment by otaviojava** [comment]
Wow! it is amazing, really thank you about this resource.
Do you have a blog? What do you think write about this resources?
When you have done, please, let me know to share to all in comunity.

**Comment by ghost** [comment]
Hi @otaviojava 

You're welcome! I'm happy that the solution we needed for my company can be reused by other people as well. I'll write the technical blog for it and let you know when it's done. Also, when can I expect the library version that contains the features I added to be available on maven repository? Some of our projects depend on them.

Thank you so much!

**Comment by otaviojava** [comment]
Yes I will do.
Pleas add this information also on the wiki: https://github.com/otaviojava/Easy-Cassandra/wiki

**Comment by ghost** [comment]
Ok. Should I add it under Features section and also under Annotations section? I can also add a link there to the technical blog I am writing. LMK

**Comment by otaviojava** [comment]
Yes under annotations sections. You may use your technical blog.

**Comment by ghost** [comment]
Done. I added it under the Annotations section: Inheritance, embedded composite keys and read by key and index range sample

**Pull request merged**
